# Generated by Django 5.2.1 on 2025-05-22 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_index=True, max_length=255)),
                ('symbol', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('scripcode', models.CharField(blank=True, max_length=50, null=True)),
                ('co_code', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pe', models.FloatField(blank=True, null=True)),
                ('roe_ttm', models.FloatField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='companies.company', to_field='co_code')),
            ],
        ),
    ]
