# Generated by Django 5.2.1 on 2025-05-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_index=True, max_length=255)),
                ('symbol', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('scripcode', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
